### PR TITLE
Jest tests, modularization, linting

### PR DESCRIPTION
**Pull request by blms**
## What this PR does

- Installs and configures jest
  - Adds tests for `index.ts` and `adjustTargetSource.ts`
- Moves `adjustTargetSource` into its own module
- Improves linting
  - Sets up linter integration with VSCode
  - Lints existing files
  - Adds linter scripts
- Rebuilds code

## Notes

- Should we include GitHub Actions for tests and coverage?
- `npm install` will need to be run to pick up new dependencies
- Test coverage is not complete, but provides a starting point for unit testing

### CODE REVIEW

**Review by rlskoeser — COMMENTED** [review]
Yes, please set up github actions for test and coverage.

What's the rationale for splitting `adjustTargetSource` into its own module?

It's possible we'll need to do other adjustments to the annotation objects when translating between annotorious and SAS, but I don't know yet.

**Comment by rlskoeser** [comment]
Forgot to mention, I was able to install and successfully ran tests locally. 

Is there an easy way to check that the linting works properly for me?

**Comment by blms** [comment]
> What's the rationale for splitting adjustTargetSource into its own module?

Basically because it's easier to unit test and mock that way! I think if we defined `AnnotationServerStorage` as a class instead of a function, it could be a method on that class, and it would be more of a typical pattern. But before, it was a function assigned to a variable inside of another function, which is an unusual pattern that complicated the testing.

It certainly could be revised by reverting it back to a function inside the `AnnotationServerStorage` function, and unit testing it in the places where it's actually called (the event handlers).

> Is there an easy way to check that the linting works properly for me?

Try adding an unused variable, or leaving off a semicolon. You should see a red underline, and at least the semicolon should be fixed on save.

> Yes, please set up github actions for test and coverage.

Will do!

**Comment by blms** [comment]
> It's possible we'll need to do other adjustments to the annotation objects when translating between annotorious and SAS, but I don't know yet.

That makes sense—for organization purposes, I wonder if something like `transforms/` could be a directory and we have modules for each of them.

**Comment by rlskoeser** [comment]
Ah, that makes sense for testing — I'd forgotten how I defined it originally, that sounds a little crazy and impossible to test.

Would the storage plugin be better/easier to work with as a class? 

I like the idea of renaming to transforms so it's more general — but ok with holding off until we know what else we need.

(One thing I think we'll need to improve is error handling when communicating with the server)

**Comment by blms** [comment]
> Would the storage plugin be better/easier to work with as a class?

I could definitely see it working that way:
- each event handler is a method on the class
- initialization is done with an `init()` function instead of calling `AnnotationServerStorage()` as a function
- `init` function binds each event handler to the client event with `on()`

Edit: or a constructor (`new AnnotationServerStorage()`) rather than `init()`, that probably makes more sense! 😛

**Comment by rlskoeser** [comment]
The class organization you describe sounds much cleaner to me. 

How much effort do you think to refactor and update the tests? Can you foresee any problems if we don't do that right now?

**Comment by blms** [comment]
Could probably have the GH actions and that done tomorrow morning sometime. I think it's better to do it sooner than later since it's a big refactor.

**Comment by rlskoeser** [comment]
@blms would it make sense for me to do some or all of the refactor so I can get familiar with the the way you've set things up and start getting used to working with jest? (it's been a while since I wrote any js tests)

**Comment by blms** [comment]
Set up workflows for tests and coverage, with a (totally arbitrary) coverage threshold of 95% of statements.

Here's the [documentation for that setting](https://jestjs.io/docs/configuration#coveragethreshold-object) in `jest.config.js`.

**Comment by rlskoeser** [comment]
> Try adding an unused variable, or leaving off a semicolon. You should see a red underline, and at least the semicolon should be fixed on save.

I had to install the ESLint extension (which I didn't previously have) — then it worked as you describe.

**Comment by blms** [comment]
Ah! Important piece, I completely forgot about installing that. I'll add it to the readme.

**Comment by rlskoeser** [comment]
forgot to mention, but the readme is really clear — thanks for documenting everything so well

**Review by rlskoeser — APPROVED** [review]

**Pull request merged**
