### PR TITLE
TypeScript conversion

### PR DESCRIPTION
**Pull request by blms**
## What this PR does

- Sets up basic `package.json`
- Sets up ESLint for TypeScript
- Sets up `tsconfig.json`
- Converts all existing code into TypeScript
- Sets up webpack
- Includes built bundle in git repo (for development purposes)

## Notes

I'm hoping it was worthwhile to convert the entire `SimpleAnnotationServerV2Adapter` file to TS. It would also have been possible to leave it as JS and simply declare its import as an `any` type, and use it in our own TS that way. However, I do think it benefits from strong typing, to ensure it conforms to the respective annotation models.

The interfaces I defined for each model aren't exhaustive, of course—and I'm wondering if someone has already done the work of writing type declarations that actually conform exactly the standard. For now, they're implemented to the minimal possible extent to work with the existing code (while avoiding `any` types).

This did lead to some pretty big changes to `SimpleAnnotationServerV2Adapter`, so I think it may be worth reviewing. Since the diff isn't working on GitHub, you might need to pull it into your own diff checker.

~~While you look at this, I'll work on webpack so you can actually use this code!~~

### CODE REVIEW

**Comment by blms** [comment]
I've set up a preliminary webpack config, built and successfully pulled in locally to geniza. However, I'm running into a curious problem. (Only realized this when I was setting `id` to an empty string at times.)

The original V2 adapter seems to do the following to convert v3 `id` into v2 `@id`:
https://github.com/Princeton-CDH/annotorious-sas-storage/blob/196dbd280be9552a04ca3b0410350c0943789aad/src/SimpleAnnotationServerV2Adapter.js#L98-L101

Otherwise, the v2 annotation's `@id` remains undefined. Therefore, I left `@id` as an optional property for v2 annotations.

But then, the original adapter can convert v2 to v3 as well. It does it in the following way, which implies that `id` could be undefined in a v3 annotation:

https://github.com/Princeton-CDH/annotorious-sas-storage/blob/196dbd280be9552a04ca3b0410350c0943789aad/src/SimpleAnnotationServerV2Adapter.js#L186-L193

Finally, in your code, we have:
```ts
    // delete an annotation
    anno.on("deleteAnnotation", (annotation: Annotation) => {
        adapter.delete(annotation.id);
    });
```
Which suggests `id` _is_ a required property for a v3 annotation.

The question I have is, how should we define these ID properties? Should we insist that they are required for one or both of v3 and v2? In that case, how should we adjust the adapter code to ensure that they are never unset?

**Comment by blms** [comment]
If I quickly patch in `adapter.delete(annotation.id || "");` to make the typescript compiler happy (ensuring `delete()` is passed a string), the plugin works completely in geniza 😄 

Included the built bundle on the branch here so you can test it out locally! Just add to `package.json` in geniza with:
```
npm install --save /path/to/annotorious-sas-storage/
```
And in `transcription.js`:
```js
import AnnotationServerStorage from "annotorious-sas-storage";
```

**Comment by rlskoeser** [comment]
> Which suggests `id` _is_ a required property for a v3 annotation.
> 
> The question I have is, how should we define these ID properties? Should we insist that they are required for one or both of v3 and v2? In that case, how should we adjust the adapter code to ensure that they are never unset?

An annotation doesn't get an id until it is saved. So a new annotation wouldn't have one yet — but you could never delete one that doesn't have an id set. 

I'm not sure if that answers how to resolve this; there must be patterns we can follow, though.

**Review by rlskoeser — APPROVED** [review]
I'm not sure how thoroughly to review! From what I can tell everything looks good.

I was able to install and build locally, and was able to use with the geniza transcription branch following your directions.

Would you stub out some preliminary instructions in the readme about setup / code organization? 

Seems ok to merge once it's documented (unless we need to resolve the annotation optional id first!)

**Pull request merged**
